### ISSUE TITLE
self::creating expects a person entry to already be present

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/People#1]
Self-made relation... and this is the result

This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
from the 11.12 CHANGELOG:
>update user and owner seeders with the ones from laravel-enso/core if they are not customized already **(optional)**

self::creating in the IsPerson trait seems to do an update; thus expecting an entry to already be there.

If I keep my existing UserSeeder configuration, the following error occurs

![image](https://user-images.githubusercontent.com/932193/46723023-293f7800-cc77-11e8-8b8e-bba50c785cc2.png)

### Steps to Reproduce
1. `migrate:fresh --seed` with a pre-11.12 userseeder (except for modifying owner to group)

### Expected behavior

Seeding to happen

### Actual behavior

Call to member function update() on null

**Comment by jlsjonas** [comment]
Note that this will also cause issues if we User::Create(...) from inside the application (as adldap2 does for us if we have a _new_ AD/LDAP user).

I still don't understand how using email as the relationship key makes sense here but that's another _issue_ 😅

**Comment by aocneanu** [comment]
>self::creating in the IsPerson trait seems to do an update; thus expecting an entry to already be there.
it is indeed

>If I keep my existing UserSeeder configuration, the following error occurs
don't use the latest one

>Note that this will also cause issues if we User::Create(...) from inside the application (as adldap2 does for us if we have a new AD/LDAP user).

use factory(User::class)->create() instead of User::create, and adapt the factory if you need so

>I still don't understand how using email as the relationship key makes sense here but that's another issue 😅
where did you saw that? we have a person_id in the user's table for the relation.

**Comment by jlsjonas** [comment]
>use factory(User::class)->create() instead of User::create, and adapt the factory if you need so

Are we really supposed to use factory() for a user creation? That does not feel like _the Laravel way_, is it? (outside of a seeder that is).

>where did you saw that? we have a person_id in the user's table for the relation.

Ye I noticed meanwhile, I saw that in a previous discussion we had. Sorry.

Seeing the actual implementation would mean I could have multiple users ( _authenticatables_ ) attached to 1 person? 👍

**Comment by jlsjonas** [comment]
>use factory(User::class)->create() instead of User::create, and adapt the factory if you need so

![image](https://user-images.githubusercontent.com/932193/46724158-bdaada00-cc79-11e8-9788-636cad36310e.png)

Causes the same issue; as the person still doesn't exist. I'm also pretty sure no library will do a `factory(User::class)->create([...])` when trying to implement a new user.

`self::creating` should just be updated to support provisioning the Person if it doesn't exist yet.

**Comment by jlsjonas** [comment]
And the factory seems to be having issues even when having the exact same code as the core `UserSeeder` (apart from an extended User; but it extends `EnsoUser` so there shouldn't be an issue there...)

**Comment by jlsjonas** [comment]
was still missing the Person... managed to seed using the new code. However the `User::create([...])` related issue is still there (I just have a _workaround_ for seeding now)

**Comment by aocneanu** [comment]
@jlsjonas in your issues you always tend to discuss about ~ 5 subjects. And in the following minutes you sort out 2/3 of them. Please be more considerate with my time. I will close this one now and I will kindly ask you to open another one per each subject. Please specify clearly if it's a bug, a question, a request, a discussion etc.

Thank you

**Comment by jlsjonas** [comment]
@aocneanu the original bug report still exist; the other comments were just related to the debugging process in trying to fix/avoid them.

the exact original bug description still exist

**Comment by aocneanu** [comment]
> I'm also pretty sure no library will do a factory(User::class)->create([...]) when trying to implement a new user. (and it definitely can't expect a tied-in Person class)

This is exactly the reason why there is a factory. And probably soon all Enso's code regarding to creating models will be moved from Models to Factories.

**Comment by jlsjonas** [comment]
>And probably soon all Enso's code regarding to creating models will be moved from Models to Factories.
From my understanding of Laravel; factories are only made to be used for seeding _(usually random)_ data; not as the _main implementation_ method, no?

**Comment by aocneanu** [comment]
Oh wow,

Factories are not invented in Laravel.

[start here](https://www.google.ro/search?q=understanding+the+factory+pattern&oq=understanding+the+factory+pattern&aqs=chrome..69i57j69i60j0l3.4411j1j1&sourceid=chrome&ie=UTF-8)

then think about situations where you need a more complex logic to create an object (like Enso's user) and where would you write it
- A in one place (factory) and use it all over the place where you need it (controllers, tests, database seeders, tinker)
- B recreating that logic all over the place
- C hiding it in magic methods, just so somebody could use a third party package and use `self::create`

take in consideration the fact that in time the app will grow to be more complex and probably you will have more people looking at the code, and you want readability, manageability and so on.
