### ISSUE TITLE
Publish does not generate configuration file

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/people#19]
Publishing the files for configuration does not generate a configuration file. I am unsure what it is meant to look like. This is the only step I had an issue with on my project where I am modifying persons to make it suit genealogy purposes more.

I need the configuration file to specify a local form and table template file. Thank you.

**Comment by aocneanu** [comment]
look at this https://github.com/laravel-enso/companies/issues/14

**Comment by curtisdelicata** [comment]
Thank you. That makes sense. I will give that an attempt.

**Comment by curtisdelicata** [comment]
Got it working. Thank you.
