### ISSUE TITLE
 Duplicate keys detected

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/People#6]
I have the following situation:
- 2 users
- 1 person
- both users belong to the same physical person

If I open people table I get the error:
`Duplicate keys detected`
and 2 lines are shown

Query for people table should be grouped by people id.

Btw.: The user_id is shown in people table and not the person_id

**Comment by mauthi** [comment]
2 other things:
- if person belongs to 1..n user e-mail should not be editable (at the moment it is readonly if person belongs to exact 1 user, if person belongs to >1 user it is not readonly)
- edit user in person edit form should not hidden if there is one than 1 user connected

**Comment by mauthi** [comment]
Ok. So the only missing thing is why the id of user is shown in people table and not the id of person.

**Comment by aocneanu** [comment]
the query behind `PeopleTable` should be:

```
return Person::select(\DB::raw(
                'people.*, people.id as "dtRowId", CASE WHEN users.id is null THEN 0 ELSE 1 END as "user"'
            ))->leftJoin('users', 'people.id', '=', 'users.person_id');
```

`people.*` will select the id of the person. There is no user.id in this select.

the request response as I see it is:

```
{id: 1, company_id: 115, title: "Mr", name: "Administrator", appellative: "Admin", uid: "admin",…}
appellative: "Admin"
birthday: "24-10-2018"
company_id: 115
created_at: "05-10-2017"
created_by: null
dtRowId: 1
email: "admin@laravel-enso.com"
id: 1
name: "Administrator"
obs: "13132222"
phone: "456"
position: "test"
title: "Mr"
uid: "admin"
updated_at: "2019-01-25 10:47:10"
updated_by: 1
user: 1
```

where `user:1` is a boolean flag.

Could you be more precise?

**Comment by mauthi** [comment]
Output:
<img width="78" alt="screenshot 2019-01-26 14 44 41" src="https://user-images.githubusercontent.com/7204559/51788002-f1523700-2178-11e9-9b81-a6b96a975bf4.png">

Response for the output above:
<img width="167" alt="screenshot 2019-01-26 14 45 57" src="https://user-images.githubusercontent.com/7204559/51788014-28284d00-2179-11e9-9b29-850079e57bde.png">

Really strange...

**Comment by aocneanu** [comment]
what's strange? You have two people, one with the id of 32 and one with 33.

**Comment by mauthi** [comment]
Yes, but in table I see 1, 2, 3, 4 which are the user ids?

**Comment by mauthi** [comment]
Ahh sorry, that table is configurated to show the line number - I changed other tables to show the id.
Sorry sorry

**Comment by aocneanu** [comment]
1,2,3,4 is the current number :D

**Comment by aocneanu** [comment]
can we close this?

**Comment by mauthi** [comment]
yes
