### ISSUE TITLE
Spelling correction: Mandatary should be Mandatory

### ISSUE THREAD

**Issue by wbovela** [laravel-enso/People#8]
This is a remark.

Prerequisites
[x ] Are you running the latest version?
[ x] Are you reporting to the correct repository?

In vendor/laravel-enso/people/Person.php the correct spelling is "Mandatory" instead of "Mandatary".

**Comment by aocneanu** [comment]
The field is used for the company's **mandatary** (representative), not to specify that something is **mandatory** (required)

**Comment by wbovela** [comment]
Learned a new word. Thanks.
